//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int kayitno { get; set; }
        public string Adisoyadi { get; set; }
        public Nullable<int> Sure { get; set; }
        public Nullable<int> Ucret { get; set; }
    }
}
