//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepaderProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int ogrno { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    }
}
